wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    is_jupyter_run: false
    python_version: 3.7.6
data-augmentation-angle:
  desc: null
  value: 11
kernel_size_l1:
  desc: null
  value: 8
lr:
  desc: null
  value: 0.007769259814266625
nn_layer_size:
  desc: null
  value: 384
out-channels-l1:
  desc: null
  value: 128
out_channel_l2:
  desc: null
  value: 12
weight-decay:
  desc: null
  value: 0.00575993370240772
